import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import type { ReactElement, ReactNode } from 'react';

import { ThemeSwitch } from '@app/components/nav/ThemeSwitch';
import { getServerTheme } from '@app/lib/themeServer';

import './globals.css';

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Test App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>): Promise<ReactElement> {
  const theme = await getServerTheme();

  return (
    <html lang="en" data-theme={theme} className={`${roboto.variable}`}>
      <body>
        <ThemeSwitch theme={theme} />
        {children}
      </body>
    </html>
  );
}
