import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';

const geistSans = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--geist-sans',
});

export const metadata: Metadata = {
  title: 'Test App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable}`}>
      <body>{children}</body>
    </html>
  );
}
